#!/usr/bin/env bash
set -euo pipefail

# Aurora — signed + notarized macOS release (arm64) + updater manifest.
#
# Produces, under src-tauri/target/aarch64-apple-darwin/release/bundle/ :
#   • dmg/Aurora_<version>_aarch64.dmg   → direct download for users
#   • macos/Aurora.app.tar.gz (+ .sig)   → updater payload
#   • latest.json                        → the updater endpoint manifest
#
# Required env for NOTARIZATION (choose ONE auth method):
#   Apple ID :  APPLE_ID  APPLE_PASSWORD(app-specific)  APPLE_TEAM_ID
#   API key  :  APPLE_API_ISSUER  APPLE_API_KEY  APPLE_API_KEY_PATH
#
# Optional:
#   DOWNLOAD_BASE  Base URL the release assets will be hosted at
#                  (default: https://github.com/mikedotjs/aurora/releases/download/v<version>)

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# --- updater signing key (generated by `tauri signer generate`, no password) ---
KEY="$HOME/.tauri/aurora-updater.key"
if [[ ! -f "$KEY" ]]; then
  echo "✗ updater key missing at $KEY" >&2
  echo "  regenerate with: bunx tauri signer generate --password '' -w $KEY" >&2
  exit 1
fi
export TAURI_SIGNING_PRIVATE_KEY
TAURI_SIGNING_PRIVATE_KEY="$(cat "$KEY")"
export TAURI_SIGNING_PRIVATE_KEY_PASSWORD=""

# --- notarization preflight ---
# NOTARY_AUTH is reused below to staple the DMG (Tauri only staples the .app).
NOTARIZE=0
NOTARY_AUTH=()
if [[ -n "${APPLE_API_KEY:-}" && -n "${APPLE_API_KEY_PATH:-}" && -n "${APPLE_API_ISSUER:-}" ]]; then
  echo "→ will notarize via App Store Connect API key"
  NOTARIZE=1
  NOTARY_AUTH=(--key "$APPLE_API_KEY_PATH" --key-id "$APPLE_API_KEY" --issuer "$APPLE_API_ISSUER")
elif [[ -n "${APPLE_ID:-}" && -n "${APPLE_PASSWORD:-}" && -n "${APPLE_TEAM_ID:-}" ]]; then
  echo "→ will notarize via Apple ID ($APPLE_ID)"
  NOTARIZE=1
  NOTARY_AUTH=(--apple-id "$APPLE_ID" --password "$APPLE_PASSWORD" --team-id "$APPLE_TEAM_ID")
else
  echo "⚠ No notarization credentials in env — the build will be SIGNED but NOT notarized." >&2
  echo "  Users would then see a Gatekeeper warning. Set APPLE_ID + APPLE_PASSWORD +" >&2
  echo "  APPLE_TEAM_ID (or the APPLE_API_ISSUER/KEY/KEY_PATH trio) to notarize. Continuing in 4s…" >&2
  sleep 4
fi

# --- build (arm64; signs with the Developer ID identity from tauri.conf.json) ---
bun tauri build --target aarch64-apple-darwin --bundles app,dmg

BUNDLE="$ROOT/src-tauri/target/aarch64-apple-darwin/release/bundle"

# --- notarize + staple the DMG itself ---
# Tauri notarizes & staples the .app, but NOT the .dmg it ships in. Staple the dmg
# too so the download carries the ticket and opens cleanly even offline / first-launch.
if [[ "$NOTARIZE" == "1" ]]; then
  DMG_FILE="$(ls "$BUNDLE"/dmg/*.dmg 2>/dev/null | head -1 || true)"
  if [[ -n "$DMG_FILE" ]]; then
    echo "→ notarizing the DMG ($(basename "$DMG_FILE"))…"
    xcrun notarytool submit "$DMG_FILE" "${NOTARY_AUTH[@]}" --wait
    xcrun stapler staple "$DMG_FILE"
    xcrun stapler validate "$DMG_FILE"
    echo "✓ DMG notarized + stapled"
  else
    echo "⚠ no .dmg found to staple — skipping DMG notarization" >&2
  fi
fi

# --- assemble the updater manifest (latest.json) ---
SIG_FILE="$(ls "$BUNDLE"/macos/*.app.tar.gz.sig 2>/dev/null | head -1 || true)"
if [[ -z "$SIG_FILE" ]]; then
  echo "✗ updater artifact (.app.tar.gz.sig) not found — is bundle.createUpdaterArtifacts true?" >&2
  exit 1
fi
VERSION="$(bun --eval 'console.log(JSON.parse(require("fs").readFileSync("src-tauri/tauri.conf.json","utf8")).version)')"
DOWNLOAD_BASE="${DOWNLOAD_BASE:-https://github.com/mikedotjs/aurora/releases/download/v$VERSION}"
PUB_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
SIG="$(cat "$SIG_FILE")"

cat > "$BUNDLE/latest.json" <<JSON
{
  "version": "$VERSION",
  "notes": "Aurora $VERSION",
  "pub_date": "$PUB_DATE",
  "platforms": {
    "darwin-aarch64": {
      "signature": "$SIG",
      "url": "$DOWNLOAD_BASE/Aurora.app.tar.gz"
    }
  }
}
JSON

echo
echo "✓ Release artifacts (v$VERSION):"
echo "  dmg:       $(ls "$BUNDLE"/dmg/*.dmg 2>/dev/null | head -1)"
echo "  updater:   ${SIG_FILE%.sig}"
echo "  manifest:  $BUNDLE/latest.json"
echo
echo "Publish at $DOWNLOAD_BASE :"
echo "  • the .dmg          — what users download & install"
echo "  • Aurora.app.tar.gz — updater payload (filename must match latest.json url)"
echo "  • latest.json       — the updater endpoint (also update tauri.conf.json endpoints[])"
